[package]
name = "ruuvitag_exporter"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = { version = "0.10" }
tokio = { version = "1", features = ["time", "sync", "rt", "macros", "rt-multi-thread"] }
tokio-stream = "0.1"
ruuvi-sensor-protocol = "0.5.0"
prometheus = { version = "0.13", default-features = false }
lazy_static = "1.4"
hyper = { version = "0.14", features = ["server", "http1", "tcp"]}
tracing = "0.1"
tracing-subscriber = "0.3"
